# Generated by Django 3.0.5 on 2020-08-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration (migrations.Migration):
    initial = True

    dependencies = [
        ('warehouse', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel (
            name='Order',
            fields=[
                ('id', models.AutoField (auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField ( )),
                ('costumer', models.ForeignKey (on_delete=django.db.models.deletion.CASCADE, to='warehouse.Customer')),
            ],
        ),
        migrations.CreateModel (
            name='OrderItem',
            fields=[
                ('id', models.AutoField (auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField ( )),
                ('price', models.PositiveIntegerField ( )),
                ('code', models.ForeignKey (on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('product', models.ForeignKey (on_delete=django.db.models.deletion.CASCADE, to='warehouse.Product')),
            ],
        ),
    ]
